name: Run Test Suites

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Check out your repository
      - run: npm i # Install dependencies
      - run: npm run coverage # Run tests and generate coverage
      - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov